### PR TITLE
Added current Foreman user as argument to hook script

### LINKED ISSUE #44: Include current user as an argument to hook scripts
For auditing purposes, it would be nice to pass the running users name (login name) as an argument to hook scripts.

### PR DESCRIPTION
**Pull request by wiad**
Resolves #44

### CODE REVIEW

**Comment by domcleal** [comment]
Thanks, but I'm worried this changes the interface significantly and is likely to cause failures in scripts checking their expected arguments. Could you pass it through as an environment variable instead?

**Comment by wiad** [comment]
ok, you mean setting the environment variable in util.rb before running the scripts? yeah, that should work, and I understand your concerns.

**Comment by wiad** [comment]
Setting the env variable via `ENV` in util.rb does not seem to carry to the hook scripts. My ruby is poor, but i guess it has to do with the way the hook scripts are called. Did you have another method in mind?

**Comment by wiad** [comment]
eh, disregard that, just have to set it in the right place... I'll get back to you with a new patch

**Pull request merged**
